[workspace]
exclude = ["solana-conformance/impl/solfuzz-agave"]
members = [
    "cli",
    "programs/*"
]
resolver = "2"

[workspace.dependencies]
agave-feature-set = { git = "https://github.com/febo/agave.git", branch = "p-token-migration" }
cbmt-program-activator = { path = "./programs/activator", version = "0.1.0" }
cbmt-program-stub = { path = "./programs/stub", version = "0.1.0" }
clap = "4.5.4"
indicatif = "0.17.8"
solana-logger = "3.0"
solana-program = "3.0"
solana-rpc = { git = "https://github.com/febo/agave.git", branch = "p-token-migration" }
solana-rpc-client = { git = "https://github.com/febo/agave.git", branch = "p-token-migration" }
solana-sdk = "3.0"
solana-system-interface = "2.0.0"
solana-test-validator = { git = "https://github.com/febo/agave.git", branch = "p-token-migration" }
termcolor = "1.4.1"
tokio = "1.37.0"

[patch.crates-io]
solana-zk-token-sdk = { git = "https://github.com/febo/agave.git", branch = "p-token-migration" }
